### ISSUE TITLE
Can we use m-lab endpoints in production application?

### ISSUE THREAD

**Issue by gsabran** [m-lab/ndt7-client-ios#78]
This project is really fantastic. It deserves many more stars, not only to appear higher on google search and save developers time!

I had a question regarding what companies can expect by using this in their production application. The code is under the Apache license, but at runtime it uses proprietary endpoints such as `locate.measurementlab.net` and the subsequent server locations.

Is there a limit on traffic we can send to those endpoints? Could those endpoint stop working or become restricted, which could create issues for live applications? I'm not suggesting none of this should happen, as we get a lot of valuable things for free here, but I was wondering if we could better describe the expectations for the SLA in that regard.

**Comment by stephen-soltesz** [comment]
Hi, @gsabran this may not be published on the website until next week, but you can get a preview by looking at https://github.com/m-lab/website/pull/620 and the associated developer page. Let us know if you still have questions. We're happy to help.

We prefer referring to an SLO (service level objective) since there is no explicit agreement (SLA).

**Comment by gsabran** [comment]
Thanks a lot!

**Comment by stephen-soltesz** [comment]
It's now live: https://www.measurementlab.net/develop/

**Comment by gsabran** [comment]
Nice!
